Feature edit backtalk survey form
ClickPop/aww-rats-client pull request #354
Opened 2022-08-01 18:02 UTC by uwemneku

- Added a new type [```SurveyFormData```](https://github.com/uwemneku/aww-rats-client/blob/e7bd0d1faca38ef83b2e2c896e8d68feee42e551/apps/backtalk/src/types/backtalk.ts#L82-L97)  which contains all the form fields of a form
- Refactored the  [```SurveyForm```](https://github.com/uwemneku/aww-rats-client/blob/feature-edit-backtalk-survey-form/apps/backtalk/src/components/backtalk/survey/SurveyForm.tsx) component such that it can be used for both creating and editing a survey form
- Added an edit button to the survey result page
- Added a [new page](https://github.com/uwemneku/aww-rats-client/blob/feature-edit-backtalk-survey-form/apps/backtalk/src/pages/results/%5Bid%5D/edit/index.tsx) for editing a survey

2022-08-11 03:20 UTC, GV14982 requested changes

2022-08-11 03:20 UTC, GV14982 commented on apps/backtalk/src/components/backtalk/results/SurveyResults.tsx
> +import { default as NextLink } from 'next/link';
We actually have a Link component already: https://github.com/ClickPop/aww-rats-client/blob/main/packages/common/components/shared/Link.tsx

2022-08-16 21:58 UTC, GV14982 commented
@uwemneku can you merge or rebase `development` into this branch? I made some changes that will hopefully fix the Vercel deployments.

2022-08-17 07:09 UTC, uwemneku commented
> @uwemneku can you merge or rebase `development` into this branch? I made some changes that will hopefully fix the Vercel deployments.

@GV14982  Yeah sure. Will get to it this weekend

2022-09-13 02:14 UTC, GV14982 approved these changes

2022-09-13 19:49 UTC, merged